### ISSUE TITLE
💡 [Feature]: Better folder structure

### ISSUE THREAD

**Issue by mverissimo** [atapas/webapis-playground#109]
**Is your feature request related to a problem? Please describe.**

During the development to improve the interface design, I'm felt lost with the current folder architecture, is very mixed the `source code` with `scripts`.

**Describe the solution you'd like**
Basically, move the source code into a folder called src. This change gives us more control over the `source code` and `scripts` like plop-file.

**Describe alternatives you've considered**

**Additional context**
 I forget to open an issue before PR #108

**Comment by atapas** [comment]
I don't have a very strong feeling about it. However, it was asked as a RFC to Next.js recently and they have added the support now.

https://nextjs.org/docs/advanced-features/src-directory
