### ISSUE TITLE
✨ [New Demo Request]: Demo with Canvas API

### ISSUE THREAD

**Issue by atapas** [atapas/webapis-playground#127]
Please include the request by answering these questions.

## What is the Example and Demo Topic?

Canvas API

## Please explain why do you need it?

Create a demo with Canvas API (Not with HTML5 Canvas tag). Please check the API link below. Please try creating multiple canvases demonstrating APIs

## Any Links, Reads?

https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API

 
## If you are picking up this request to implement, PLEASE READ THIS

- [HOW TO ADD A DEMO](https://github.com/atapas/webapis-playground/blob/master/HOW-TO-ADD-DEMO.md)

**Comment by richardnikolas** [comment]
Hey @atapas , I would love to contribute in this. Could you assign this to me?
