### ISSUE TITLE
✨ [New Demo Request]: Pointer Capture API Demo

### ISSUE THREAD

**Issue by atapas** [atapas/webapis-playground#131]
Please include the request by answering these questions.

## What is the Example and Demo Topic?

Pointer events

## Please explain why do you need it?

Pointer events are DOM events that are fired for a pointing device. They are designed to create a single DOM event model to handle pointing input devices such as a mouse, pen/stylus or touch (such as one or more fingers).

The pointer is a hardware-agnostic device that can target a specific set of screen coordinates. Having a single event model for pointers can simplify creating Web sites and applications and provide a good user experience regardless of the user's hardware.

## Any Links, Reads?

https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events

 
## If you are picking up this request to implement, PLEASE READ THIS

- [HOW TO ADD A DEMO](https://github.com/atapas/webapis-playground/blob/master/HOW-TO-ADD-DEMO.md)

**Comment by supminn** [comment]
I would like to take this up. Could you please assign it to me.
