### ISSUE TITLE
💡 [Feature]: Proposing minor edits in HOW-TO-ADD-DEMO.md

### ISSUE THREAD

**Issue by vaibhav-if** [atapas/webapis-playground#136]
**Is your feature request related to a problem? Please describe.**
The text [*Would you please create a branch for the issue?*](https://github.com/atapas/webapis-playground/blob/master/HOW-TO-ADD-DEMO.md#3-create-a-branch) implies that a question is being asked whether the contributor will perform this step or not. 

**Describe the solution you'd like**
I think it would be better to replace it with *Please create a branch for the issue.* to better imply an instruction.

**Describe alternatives you've considered**

**Additional context**
This same issue can also be found here [*Would you please provide a feature URL*](https://github.com/atapas/webapis-playground/blob/master/HOW-TO-ADD-DEMO.md#4-add-a-demo).

What is your opinion on it? @atapas 

If the team agrees on it can I make the proposed changes?

**Comment by atapas** [comment]
Go ahead.
