### ISSUE TITLE
✨ [New Demo Request]: Add the Geolocation Demo

### ISSUE THREAD

**Issue by atapas** [atapas/webapis-playground#14]
Please include the request by answering these questions.

## What is the Example and Demo Topic?

Add a demo of the Geolocation API(https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API)

## Please explain why do you need it?

It is a most used web API. It would be nice to have an API Demo for this one

## Any Links, Reads?

https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API

## Do you want to contribute to the source code for this example?

Yes.

## If you are picking up this request to implement, PLEASE READ THIS

- [HOW TO ADD A DEMO](https://github.com/atapas/webapis-playground/blob/master/HOW-TO-ADD-DEMO.md)

**Comment by wsameer** [comment]
Hi @atapas , I would like to work on this issue.

**Comment by atapas** [comment]
> Hi @atapas , I would like to work on this issue.

@wsameer, It's all yours now. All the best, If you need any info or want to discuss anything, please open up a discussion here https://github.com/atapas/webapis-playground/discussions
