### ISSUE TITLE
✨ [New Demo Request]: The Page Visibility API Demo

### ISSUE THREAD

**Issue by williamssam** [atapas/webapis-playground#154]
Please include the request by answering these questions.

## What is the Example and Demo Topic?
Page Visibility API

## Please explain why do you need it?
Let’s say that you want to check if the page is currently focused before executing something. The Page Visibility API has been designed for this purpose and provides events you can watch to know when a document becomes visible or hidden. This means that when the user minimizes the window or switches to another tab, an event will be sent.

## Any Links, Reads?

[<ADD HERE>](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API)

## Do you want to contribute to the source code for this example?

Yes
  
## If you are picking up this request to implement, PLEASE READ THIS

- [HOW TO ADD A DEMO](https://github.com/atapas/webapis-playground/blob/master/HOW-TO-ADD-DEMO.md)

**Comment by atapas** [comment]
@williamssam Are you able to get started?

**Comment by williamssam** [comment]
Yes

**Comment by williamssam** [comment]
Hi @atapas I just made a PR for this Issue, kindly check
