### ISSUE TITLE
✨ [New Demo Request]:  EyeDropper API

### ISSUE THREAD

**Issue by williamssam** [atapas/webapis-playground#158]
## What is the Example and Demo Topic?

EyeDropper API

## Please explain why do you need it?

The EyeDropper API provides a mechanism for creating an eyedropper tool. Using this tool, users can sample colors from their screens, including outside of the browser window.

## Any Links, Reads?

https://developer.mozilla.org/en-US/docs/Web/API/EyeDropper_API

## Do you want to contribute to the source code for this example?

Yes
  
## If you are picking up this request to implement, PLEASE READ THIS

- [HOW TO ADD A DEMO](https://github.com/atapas/webapis-playground/blob/master/HOW-TO-ADD-DEMO.md)

**Comment by sohailg** [comment]
i would like to work on it,can you help me with the process

**Comment by atapas** [comment]
> i would like to work on it,can you help me with the process

It's assigned already! You can pick another one from the issue list.

**Comment by williamssam** [comment]
> i would like to work on it,can you help me with the process

@sohailg I'm already working on this. You can create a new issue to work on.

**Comment by sohailg** [comment]
ok, All the Best
