### ISSUE TITLE
✨ [New Demo Request]: WebRTC Api

### ISSUE THREAD

**Issue by williamssam** [atapas/webapis-playground#164]
## What is the Example and Demo Topic?

WebRTC API

## Please explain why do you need it?

WebRTC (Web Real-Time Communication) is a technology that enables Web applications and sites to capture and optionally stream audio and/or video media, as well as to exchange arbitrary data between browsers without requiring an intermediary. 

## Any Links, Reads?

https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API

## Do you want to contribute to the source code for this example?

yes
  
## If you are picking up this request to implement, PLEASE READ THIS

- [HOW TO ADD A DEMO](https://github.com/atapas/webapis-playground/blob/master/HOW-TO-ADD-DEMO.md)

**Comment by raveenita** [comment]
I want to! Pleasee. This one! @williamssam can you assign to me?  <3

**Comment by williamssam** [comment]
@atapas please assign this to @raveenita, thanks

**Comment by atapas** [comment]
> @atapas please assign this to @raveenita, thanks

Done

**Comment by raveenita** [comment]
Thank u, I love this API <3

**Comment by atapas** [comment]
> Thank u, I love this API <3

Looking forward to it.

**Comment by raveenita** [comment]
@atapas  I have opened the PR here: https://github.com/atapas/webapis-playground/pull/186
Waiting for you review <3
