### ISSUE TITLE
🐛 [Bug]: Canvas API Flag rendering issue

### ISSUE THREAD

**Issue by ansh-saini** [atapas/webapis-playground#171]
**Describe the bug**
When you press the 'Show canvases' button multiple times it breaks the flag

**To Reproduce**

1. Go to https://webapis-playground.vercel.app/demo/canvas-api
2. Click on Show Canvases multiple times

**Expected behavior**
Flag should stay the same.

**Screenshots**
![image](https://user-images.githubusercontent.com/32511936/195277390-3ce08355-20de-4055-a646-720fe9ba3223.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome
- Version: Latest

**Comment by ansh-saini** [comment]
I would like to work on this

**Comment by atapas** [comment]
> I would like to work on this

Please take it.

**Comment by rnsharma10** [comment]
@atapas I have already completed the fix.
@ansh-saini May be you can take a look at my code to check.

**Comment by rnsharma10** [comment]
@atapas You can take a look at these bugs for which fix is already developed but need to be pushed.
https://github.com/atapas/webapis-playground/issues/175
https://github.com/atapas/webapis-playground/issues/176
