### ISSUE TITLE
💡 Use Tailwindcss for the project

### ISSUE THREAD

**Issue by atapas** [atapas/webapis-playground#22]
**Is your feature request related to a problem? Please describe.**
Right now the project uses a `global.css` file under https://github.com/atapas/webapis-playground/blob/master/styles/globals.css. The aim is to move to use [Tailwindcss](https://tailwindcss.com/#what-is-tailwind).

The support for Tailwind to work with a Next.js project is already done and available in the codebase.

**Describe the solution you'd like**
Use https://tailwindcss.com/#what-is-tailwind

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by tiger-yash** [comment]
hello! 
I would I would like to work on this issue, can you please assign it to me?

**Comment by atapas** [comment]
> hello! 
> I would I would like to work on this issue, can you please assign it to me?

You got it 🙂
