### ISSUE TITLE
✨ [New Demo Request]: Create a Web Speech API Demo

### ISSUE THREAD

**Issue by atapas** [atapas/webapis-playground#23]
Please include the request by answering these questions.

## What is the Example and Demo Topic?

Web Speech API Demo. You can read it from [here](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API)

## Please explain why do you need it?

The Web Speech API enables you to incorporate voice data into web apps. It will be great to show how to handle voice data.

## Any Links, Reads?

https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API

  
## If you are picking up this request to implement, PLEASE READ THIS

- [HOW TO ADD A DEMO](https://github.com/atapas/webapis-playground/blob/master/HOW-TO-ADD-DEMO.md)

**Comment by Abiola-Farounbi** [comment]
Hi, I would like to work on this issue.

**Comment by atapas** [comment]
Helo @Abiola-Farounbi , assigned to you. Thanks.
