### ISSUE TITLE
✨ [New Demo Request]: Screen Capture API Demo

### ISSUE THREAD

**Issue by atapas** [atapas/webapis-playground#24]
Please include the request by answering these questions.

## What is the Example and Demo Topic?

The Screen Capture API introduces additions to the existing Media Capture and Streams API to let the user select a screen or portion of a screen (such as a window) to capture as a media stream. This stream can then be recorded or shared with others over the network.

## Please explain why do you need it?

A screen capture can be useful in many cases to be embedded within the application. A demo of how it works and how to implement using the code will be great.

## Any Links, Reads?

https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API

 
## If you are picking up this request to implement, PLEASE READ THIS

- [HOW TO ADD A DEMO](https://github.com/atapas/webapis-playground/blob/master/HOW-TO-ADD-DEMO.md)

**Comment by koustov** [comment]
May i take this one @atapas
