### ISSUE TITLE
🐛 Improve the accesibility score

### ISSUE THREAD

**Issue by atapas** [atapas/webapis-playground#26]
**Describe the bug**
The lighthouse score of the accessibility of not that great yet. Please improve it.

**To Reproduce**
Open the app and run lighthouse from the browser console.
Check the report.

**Expected behavior**
The score should be >= 95

**Screenshots**
![image](https://user-images.githubusercontent.com/3633137/135240965-e84b688f-7d91-4cf6-85b6-49c595c62c53.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by niteshseram** [comment]
Hello @atapas, I would like to work on this if you are not working on this.

**Comment by niteshseram** [comment]
But I see the accessibility score as 92 for the homepage when I run the lighthouse. Is the above score you have added for the homepage?

**Comment by atapas** [comment]
Hey @niteshseram, Yes I see it on the home page only. It also reports a few issues in the audit that could help it to be better

![image](https://user-images.githubusercontent.com/3633137/135267980-fa2482cc-07d4-45d8-a21d-39408276820b.png)

**Comment by niteshseram** [comment]
Okay sure. So, it is okay right if I take up this issue?

**Comment by atapas** [comment]
@niteshseram I have assigned it to you.. so it all yours :).

Thanks for taking it up.

**Comment by niteshseram** [comment]
Thanks

**Comment by niteshseram** [comment]
@atapas I made the accessibility 100 but I don't see this `aria` related accessibility issue in my local.

**Comment by atapas** [comment]
> @atapas I made the accessibility 100 but I don't see this `aria` related accessibility issue in my local.

Great, Awesome!!! Please create a PR and let us test it once on the deployed link?

**Comment by niteshseram** [comment]
Yes, I just made a PR

**Comment by atapas** [comment]
ok I saw the preview link and ran lighthouse.. I see a great improvement in the score @niteshseram 

But I see that aria error too..

![image](https://user-images.githubusercontent.com/3633137/135272371-f07a46a5-0e84-4a8f-81cd-a33b4f28f89a.png)


I am on Chrome
I am on non-cognito mode.

**Comment by atapas** [comment]
Here is the preview link: https://webapis-playground-git-fork-niteshseram-fix-c6d34b-thoughtdump.vercel.app

**Comment by niteshseram** [comment]
Okay, I got it @atapas. In Non-Cognito, the plugin does this. I was running in cognito mode.

**Comment by niteshseram** [comment]
I don't think we can't do anything about it. The plugin itself injects some code.

**Comment by atapas** [comment]
Yeah, I agree, I saw it is 100% in the incognito mode.

**Comment by niteshseram** [comment]
Yes, for example, I am using Grammerly extension, so Grammarly injects some code at the bottom of our website and we can't do anything about it.

**Comment by atapas** [comment]
@niteshseram go ahead and request the review.. Let me try merging it today itself :).

**Comment by niteshseram** [comment]
Request for review? I didn't get @atapas.

**Comment by atapas** [comment]
> Request for review? Sorry, I didn't get you there @atapas.

No worries, I did it. I meant this one

![image](https://user-images.githubusercontent.com/3633137/135275545-d5980955-feca-48ed-b4f8-86d7a54cd476.png)

**Comment by niteshseram** [comment]
I don't think I can do that.

**Comment by niteshseram** [comment]
There was no option

**Comment by atapas** [comment]
No worries, I realized that now :)

I have posted a tiny comment in the PR.
