### ISSUE TITLE
💡 [Feature]: Design a landing page of the playground

### ISSUE THREAD

**Issue by atapas** [atapas/webapis-playground#27]
**Is your feature request related to a problem? Please describe.**
No, it is an enhancement request. It would  be great to have a landing page indicating,
- What is the purpose of this playground?
- What kind of demos are available so far?
- How to add a new demo info
- Link to GitHub
- Social handles to share the app
- Contact information
- Contributor information
- Many more

**Describe the solution you'd like**
First, I would like to get a design proposal for the app landing page basis on the above points. Then we can go for implementations.

**Describe alternatives you've considered**
The alternative is the current landing page

**Additional context**
Here is an example of an attractive and informative landing page: https://tryshape.vercel.app/

**Comment by bharati-21** [comment]
/hey @atapas ,
I'd like to work on this!

**Comment by atapas** [comment]
> Hey @atapas , I'd like to work on this!

Great, you are on it. I have some thoughts around this but open to any ideas. Please let me know if you are available to have a short sync up sometime this weekend.

**Comment by bharati-21** [comment]
> > Hey @atapas , I'd like to work on this!
> 
> Great, you are on it. I have some thoughts around this but open to any ideas. Please let me know if you are available to have a short sync up sometime this weekend.

Cool, does Sunday work for you?

**Comment by atapas** [comment]
> > > Hey @atapas , I'd like to work on this!
> > 
> > 
> > Great, you are on it. I have some thoughts around this but open to any ideas. Please let me know if you are available to have a short sync up sometime this weekend.
> 
> Cool, does Sunday work for you?

Yes.

**Comment by bharati-21** [comment]
Hi @atapas,
Please do tell me a time suitable for you so that I can setup a meet!

Thanks :)

**Comment by atapas** [comment]
> Hi @atapas, Please do tell me a time suitable for you so that I can setup a meet!
> 
> Thanks :)

How about 2pm? Please set it up. Please DM me here, we can do it at run time too.. :)

https://twitter.com/tapasadhikary

**Comment by atapas** [comment]
@bharati-21 https://github.com/atapas/webapis-playground/issues/51#issuecomment-933120015

FYI...

**Comment by atapas** [comment]
Thanks @bharati-21 closing this issue. Please retain the link to help the implementation.

**Comment by atapas** [comment]
@all-contributors please add @bharati-21  for Design
