### ISSUE TITLE
💡 [Feature]: Add the See Code button in the demo details page

### ISSUE THREAD

**Issue by atapas** [atapas/webapis-playground#28]
**Is your feature request related to a problem? Please describe.**
The demo details page doesn't have the source code link. Please provide a link to the relevant source code from the demo page.

![image](https://user-images.githubusercontent.com/3633137/135266174-0157ece2-5646-4189-932c-05dca9ae3af1.png)

**Describe the solution you'd like**
I would like to get a demo link from the demo details page.

**Describe alternatives you've considered**
The present alternative is to come to the landing page and go to the code.

**Additional context**
None.

**Comment by aanchal-fatwani** [comment]
Hi, I would like to work on this issue. Please assign the same.

**Comment by atapas** [comment]
> Hi, I would like to work on this issue. Please assign the same.

Done!
