### ISSUE TITLE
🐛 [Bug]: Typo in readme

### ISSUE THREAD

**Issue by niteshseram** [atapas/webapis-playground#31]
**Describe the bug**
There are some typos in the readme.
**Fixes:** 
- `yan` to `yarn`
- Make the yarn command in a new line separated by `# or` in the next line

![Capture](https://user-images.githubusercontent.com/51370246/135287621-d2de028f-358d-458c-a16d-78c7e2e1625b.PNG)

**Comment by atapas** [comment]
@niteshseram are you taking it up to fix?

**Comment by niteshseram** [comment]
If you want I can jump in.

**Comment by atapas** [comment]
Go ahead, you are on fire!!!

**Comment by niteshseram** [comment]
I can take up more issues but I will do that after 1st Oct 🤣 . This pull request will not be counted in Hacktoberfest. Never took part in Hacktoberfest so I really want to participate this time.

**Comment by atapas** [comment]
> I can take up more issues but I will do that after 1st Oct 🤣 . This pull request will not be counted in Hacktoberfest. Never took part in Hacktoberfest so I really want to participate this time.

Sure thing. Do not raise a PR now. Let's do the PR after 1st.

**Comment by niteshseram** [comment]
> > I can take up more issues but I will do that after 1st Oct 🤣 . This pull request will not be counted in Hacktoberfest. Never took part in Hacktoberfest so I really want to participate this time.
> 
> Sure thing. Do not raise a PR now. Let's do the PR after 1st.

You can merge this one if you want. I already made the PR. Since it is a typo in the steps of setting up the project locally, if a complete beginner comes in, it will be a problem for them.
