### ISSUE TITLE
💡 [Feature]: Make the app as Progressive Web App(PWA)

### ISSUE THREAD

**Issue by atapas** [atapas/webapis-playground#39]
**Is your feature request related to a problem? Please describe.**
No. It is a feature request to make this app a Progressive Web APP

**Comment by niteshseram** [comment]
Can I take this up?

**Comment by atapas** [comment]
> Can I take this up?

Assigned

**Comment by niteshseram** [comment]
The logo inside `public/readme` is the logo of the project?

**Comment by atapas** [comment]
> The logo inside `public/readme` is the logo of this project?

Nope. Need to make one on the same line.. also favicon on the same line.

**Comment by niteshseram** [comment]
While doing PWA, we need logo. So, for time being should I just use the vercel logo?

**Comment by atapas** [comment]
@niteshseram Yes, I will get a logo by tomorrow. We will replace it then
