### ISSUE TITLE
💡 [Feature]: Add a search capability in the demo listing page

### ISSUE THREAD

**Issue by atapas** [atapas/webapis-playground#43]
Add a search mechanism in the demo list page to search the demo by its name. Please feel free to open a discussion about your design proposal.

![image](https://user-images.githubusercontent.com/3633137/135588882-efb38e8e-b4ff-470c-9b59-79b6ec31ae0a.png)

**Comment by omriattiya** [comment]
Hi, can you assign me this issue?

**Comment by atapas** [comment]
> Hi, can you assign me this issue?

You got it
