### ISSUE TITLE
💡 [Feature]: Design a logo for webapis playground

### ISSUE THREAD

**Issue by atapas** [atapas/webapis-playground#45]
**Is your feature request related to a problem? Please describe.**
Yes, the current logo used is the vercel logo.

**Describe the solution you'd like**
Design and transparent logo and commit. The existing logo is here:

https://github.com/atapas/webapis-playground/blob/master/public/readme/Logo.png

The new logo design should be on the same line but with transparent background.

The same logo will be used to create favicons too

**Comment by kvnal** [comment]
I would like to work on this (SVG or PNG ?), Please assign me this task

**Comment by atapas** [comment]
> I would like to work on this (SVG or PNG ?), Please assign me this task

Done!

Lets create both. PNG mandatory

**Comment by kvnal** [comment]
> > I would like to work on this (SVG or PNG ?), Please assign me this task
> 
> Done!
> 
> Lets create both. PNG mandatory

PR created #57 👈 pls review.
Thanks!

**Comment by atapas** [comment]
Done
