### ISSUE TITLE
🐛 [Bug]: A few demo interface breaks in the mobile resolution

### ISSUE THREAD

**Issue by atapas** [atapas/webapis-playground#53]
**Describe the bug**
These demos are breaking in a smaller resolution.

- https://webapis-playground.vercel.app/demos/picture-in-picture
- https://webapis-playground.vercel.app/demos/filesystem-api
- https://webapis-playground.vercel.app/demos/broadcast-channel
- https://webapis-playground.vercel.app/demos/vibration
- https://webapis-playground.vercel.app/demos/image-capture
Kindly check all other demos also

**Expected behavior**
The UI shouldn't break in responsive mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/3633137/135711792-66ebf29b-f62c-48a7-a148-efbb683fe86b.png)

![image](https://user-images.githubusercontent.com/3633137/135711800-0f2cdd58-7e66-491d-ba10-e862c040345f.png)

![image](https://user-images.githubusercontent.com/3633137/135711823-4edbe27e-6741-400b-8caf-d6f9c1e18b97.png)

![image](https://user-images.githubusercontent.com/3633137/135711875-2f6146cd-2090-49c9-a29a-b1bc2bf72aae.png)

![image](https://user-images.githubusercontent.com/3633137/135711920-a971793a-9c8c-4cdf-a3fc-c7f0b0111e39.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AhsanAyaz** [comment]
I AM WORKING ONNNN THISSSSSS!!! 
PLEASEEEEE DOOOOOO NOAAAAAAT PICCCKKKK THISSSSSSSSSS ONEEEEEE!
jk

**Comment by AhsanAyaz** [comment]
I'm working on this issue. To demonstrate to my stream on [twitch](https://twitch.tv/CodeWithAhsan) & [YouTube](https://youtube.com/c/CodeWithAhsan) about how to contribute to GitHub repositories in Hacktoberfest

**Comment by iUseYahoo** [comment]
there is a issue

**Comment by RajputUsman** [comment]
> I AM WORKING ONNNN THISSSSSS!!! PLEASEEEEE DOOOOOO NOAAAAAAT PICCCKKKK THISSSSSSSSSS ONEEEEEE! jk

[You comedy Me](https://tenor.com/view/are-you-comedy-me-gif-22462710)

**Comment by atapas** [comment]
> I AM WORKING ONNNN THISSSSSS!!! 
> PLEASEEEEE DOOOOOO NOAAAAAAT PICCCKKKK THISSSSSSSSSS ONEEEEEE!
> jk

GO FOR ITTTTTTT
