### ISSUE TITLE
💡 [Feature]: move img to Image tag from next/image

### ISSUE THREAD

**Issue by niteshseram** [atapas/webapis-playground#56]
**Is your feature request related to a problem? Please describe.**
We should use `<Image />` from `next/image` in place of `img` element. 

**Describe the solution you'd like**
Using Next.js image helps us in lazy loading, image optimization and serves the image as `.webp` format
I don't know if there was some reason for using `img` element in the first place

**Comment by rehan-sattar** [comment]
Hi @niteshseram, picking this one! PR coming soon :rocket:

**Comment by niteshseram** [comment]
@rehan-sattar Thanks for taking up the issue. But I would like to wait for a reply from @atapas to see if this feature is needed or not. Don't yet start, let him confirm and assign you

**Comment by rehan-sattar** [comment]
Oh, Thanks for informing me! Waiting :smiley:

**Comment by atapas** [comment]
Not fixing
