### ISSUE TITLE
🐛 [Bug]: Images inside the buttons are not aligned properly.

### ISSUE THREAD

**Issue by rehan-sattar** [atapas/webapis-playground#59]
**Describe the bug**

The images inside of the buttons are not aligned properly. 

**Screenshots**
![image](https://user-images.githubusercontent.com/26999472/135722173-504bb922-f73e-49b4-b4a0-6ddeebc37e5e.png)

PS: I can fix it straight away if I get a green signal for it. :sweat_smile:

**Comment by atapas** [comment]
@rehan-sattar All yours
