### ISSUE TITLE
💡 [Feature]: Make the header sticky

### ISSUE THREAD

**Issue by atapas** [atapas/webapis-playground#73]
When we scroll, the header scrolls. That's not so intuitive. Let's make it sticky.

Applicable to both demo landing and individual demo pages.

**Comment by abhikhatri67** [comment]
Hey @atapas, can you assign me this issue?

**Comment by atapas** [comment]
> Hey @atapas, can you assign me this issue?

All yours

**Comment by abhikhatri67** [comment]
> > Hey @atapas, can you assign me this issue?
> 
> All yours

Thanks.

**Comment by abhikhatri67** [comment]
@atapas Created PR for it.
