### ISSUE TITLE
API doc link

### ISSUE THREAD

**Issue by Sukhseerat-Kaur** [atapas/webapis-playground#79]
The api name should ne linked to the api's documentation. Assign me this issue, I can work on it.

**Comment by atapas** [comment]
@Sukhseerat-Kaur I have assigned it to you. Could you please explain the issue a bit more? Maybe a screenshot and what is expected would be helpful for me to understand and accept the fix faster. Thanks.

**Comment by atapas** [comment]
Hi @Sukhseerat-Kaur Are you still working on this issue?

**Comment by vaibhav-if** [comment]
Hi @atapas the [API Names](https://github.com/atapas/webapis-playground#-whats-included), can be linked to either the respective api's page or to the api's source code.
Where do you think it should be linked to?
Also, when contributors add their API to readme.md, will they have a url to link the API's name to?

If @Sukhseerat-Kaur is not working on it, can I take this issue?

**Comment by atapas** [comment]
It has been done as part of the refactoring made my @mverissimo. I'm closing this issue.

**Comment by atapas** [comment]
Hi @Sukhseerat-Kaur 

Thanks a lot for opening the issue and making the app better. Please feel free to contribute more. You will be added to the contribution list. Don't forget to share about your contribution publicly and provide your support with a star ⭐.

Great work 🔥 !!!!

**Comment by atapas** [comment]
@all-contributors please add @Sukhseerat-Kaur  for Bug
